BUILD_DIR=bin
CMD_DIR=cmd
INSTALL_BIN_DIR=$(HOME)/bin
CONFIG_DIR=$(HOME)/.config/mcp-kit

GO=go
GOFLAGS=-ldflags="-s -w"

# Auto-discover binaries from cmd/*.
APPS := $(notdir $(wildcard $(CMD_DIR)/*))

.PHONY: all help build clean tidy install

all: build

## ❓ Show available targets
help:
	@echo "Available targets:"
	@awk 'BEGIN {FS = ":.*##"} \
		/^## / { doc = substr($$0, 4); next } \
		/^[a-zA-Z_%-]+:/ && doc { \
			printf "  \033[36m%-20s\033[0m %s\n", substr($$1, 1, index($$1, ":") - 1), doc; \
			doc = "" \
		} \
		/^$$/ { doc = "" }' $(MAKEFILE_LIST)
	@echo ""
	@echo "Binaries (cmd/*): $(APPS)"
	@echo "  build-<app>"

## 🔨 Build all binaries (linux amd64, stripped)
build: $(APPS:%=build-%)

## 📥 Copy binaries to ~/bin/ and create config files in ~/.config/mcp-kit/
install: build
	@mkdir -p $(INSTALL_BIN_DIR) $(CONFIG_DIR)
	@for app in $(APPS); do \
		echo "==> Installing $$app -> $(INSTALL_BIN_DIR)/$$app"; \
		install -m 0755 $(BUILD_DIR)/$$app $(INSTALL_BIN_DIR)/$$app; \
		cfg="$(CONFIG_DIR)/$$app.env"; \
		tpl="$(CMD_DIR)/$$app/.env.dist"; \
		if [ -f "$$cfg" ]; then \
			echo "    config: $$cfg (exists, skipped)"; \
		elif [ -f "$$tpl" ]; then \
			cp "$$tpl" "$$cfg"; chmod 600 "$$cfg"; \
			echo "    config: $$cfg (from template $$tpl)"; \
		else \
			: > "$$cfg"; chmod 600 "$$cfg"; \
			echo "    config: $$cfg (empty)"; \
		fi; \
	done

## 🧹 Clean
clean:
	@echo "==> Cleaning..."
	rm -rf $(BUILD_DIR)

## 📦 Dependencies
tidy:
	@echo "==> Tidying modules..."
	$(GO) mod tidy

# Per-app build targets generated by foreach.
define APP_RULES
.PHONY: build-$(1)

build-$(1):
	@echo "==> Building $(1)..."
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 $$(GO) build $$(GOFLAGS) -o $$(BUILD_DIR)/$(1) ./$$(CMD_DIR)/$(1)
endef

$(foreach app,$(APPS),$(eval $(call APP_RULES,$(app))))
